URL="https://downloads.sourceforge.net/project/bluestarlinux/distro/bluestar-linux-REPLACE_VERSION-x86_64.iso"
TYPE=file
CONTENTS="\
arch/x86_64/airootfs.sfs|airootfs.sfs
arch/boot/x86_64/archiso.img|initrd
arch/boot/x86_64/vmlinuz|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="arch-xz"
